name: Labeler
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - id: label-PR
        uses: actions/labeler@v5
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        if: contains(steps.label-PR.outputs.all-labels, 'TEAM1')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const teamName = 'idarktagorg/dark-team'
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ vars.TEAM_1 }} team'
            })
